/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
#include "GPIO.h"
#include "SPI.h"


void delay(){
	for(int i=0;i<500000;i++);
}


/*
 * Protypes for GPIO test functions

void GPIO_Configure_LED();
void GPIO_Configure_BTN();
void EXTI4_IRQHandler(void);
void EXTI9_5_IRQHandler(void);
void EXTI15_10_IRQHandler(void);

*/


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /*
     * GPIO Configurations
     */
	//GPIO_Configure_LED();
	//GPIO_Configure_BTN();



	for(;;){
	}
}



/*
 * GPIO FUNCTIONality tests
 *
 *

void GPIO_Configure_LED(){

	//enable the clk for the GPIOA
	GPIO_ChangeClk(GPIOC,ENABLE);
	//configure pin5 as output
	GPIO_PINHandle *pin_conf = malloc(sizeof(GPIO_PINHandle));
	pin_conf->Config.pin_mode = OUTPUT;
	pin_conf->Config.otype = PushPull;
	pin_conf->PIN = GPIO_PIN_13;
	pin_conf->port = GPIOC;

	GPIO_Init(pin_conf);
	free(pin_conf);

}


void GPIO_Configure_BTN(){

	//enable the clk for the GPIOA
	GPIO_ChangeClk(GPIOB,ENABLE);
	//configure pin5 as output
	GPIO_PINHandle *pin_conf = malloc(sizeof(GPIO_PINHandle));
	pin_conf->Config.pin_mode = IRQ_FE;
	pin_conf->Config.pupd = PD;
	pin_conf->PIN = GPIO_PIN_10;
	pin_conf->port = GPIOB;

	GPIO_Init(pin_conf);
	free(pin_conf);
	GPIO_IRQEnable(IRQ_N_EXTI15_10 , ENABLE);
	GPIO_IRQPriority(IRQ_N_EXTI15_10,  14);
}

void EXTI4_IRQHandler(void){
	GPIO_IRQHandling(4);
}

void EXTI9_5_IRQHandler(void){
	GPIO_IRQHandling(6);
	GPIO_TogglePin(GPIOC_BA, GPIO_PIN_13);
}

void EXTI15_10_IRQHandler(void){
	GPIO_IRQHandling(10);
	GPIO_TogglePin(GPIOC_BA, GPIO_PIN_13);
}


*/





